apiVersion: v1
kind: Service
metadata:
  name: basic-akka-http-app-service

spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
    app: basic-akka-http-app
